version: '3'
services:
  redis:
    container_name: redis-curseproxy
    restart: always
    image: redislabs/redismod:latest
    ports:
      - "6379:6379"
    networks:
      - code-network
networks:
  code-network:
    driver: bridge